// Generated by CoffeeScript 1.10.0
(function() {
  app.directive("artist", function() {
    return {
      restrict: "E",
      scope: {
        intro: "="
      },
      templateUrl: "../../View/partial/_artist.html",
      transclude: true,
      replace: true
    };
  });

}).call(this);

//# sourceMappingURL=artist.js.map
