// Generated by CoffeeScript 1.10.0
(function() {
  app.directive("selectBox", function() {
    return {
      restrict: "A",
      link: function($scope, element, attrs) {}
    };
  });

}).call(this);

//# sourceMappingURL=selectBox.js.map
