// Generated by CoffeeScript 1.10.0
(function() {
  app.filter("nameModel", [
    function() {
      return function(name, model) {
        if (model === "INIT") {
          return name.substr(0, 1);
        }
        return name;
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=nameModel.js.map
