// Generated by CoffeeScript 1.10.0
(function() {
  app.filter("trusted", [
    "$sce", function($sce) {
      return function(url) {
        return $sce.trustAsResourceUrl(url);
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=trusted.js.map
